In [127]:
import pandas as pd

In [133]:
OLD_PAD = "C:/Users/Jerome/Dropbox/PC/Downloads/all_complexities_skeletonised_analysis.csv"
OLD_STRETCH = "C:/Users/Jerome/Dropbox/PC/Downloads/all_complexities_stretch_analysis.csv"
NEW = "C:/Users/Jerome/Documents/hanzi_data/complexities/all_complexities.csv"

In [134]:
old_pad = pd.read_csv(OLD_PAD, index_col=0)
old_stretch = pd.read_csv(OLD_STRETCH, index_col=0)

new = pd.read_csv(NEW, index_col=0)

C:\Users\Jerome\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\Jerome\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\Jerome\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [137]:
old_pad = old_pad.rename({"original character": "original_character", "ID": "image_ID", "perimetric complexity": "old_perimetric_complexity", "pixel complexity": "old_pixel_complexity", "scale method": "scale_method"}, axis=1)
print(old_pad.shape)
print(old_pad.columns)
old_stretch = old_stretch.rename({"original character": "original_character", "ID": "image_ID", "perimetric complexity": "old_perimetric_complexity", "pixel complexity": "old_pixel_complexity", "scale method": "scale_method"}, axis=1)
print(old_stretch.shape)
print(old_stretch.columns)

old = pd.concat([old_pad, old_stretch], axis=0)
print(old.shape)
old.head()

(742756, 11)
Index(['character id', 'original_character', 'simplified character', 'period',
       'image_ID', 'scale_method', 'skeletonise method', 'dataset',
       'old_perimetric_complexity', 'old_pixel_complexity',
       'character stream'],
      dtype='object')
(742756, 10)
Index(['character id', 'original_character', 'simplified character', 'period',
       'image_ID', 'scale_method', 'skeletonise method', 'dataset',
       'old_perimetric_complexity', 'old_pixel_complexity'],
      dtype='object')
(1485512, 11)

,character id,original_character,simplified character,period,image_ID,scale_method,skeletonise method,dataset,old_perimetric_complexity,old_pixel_complexity,character stream
0,c0,一,一,Bronze,B00001,pad,lee,hanziyuan,73.284496,288.0,Oracle
1,c0,一,一,Bronze,B00002,pad,lee,hanziyuan,79.877128,301.0,Oracle
2,c0,一,一,Bronze,B00003,pad,lee,hanziyuan,75.816740,286.0,Oracle
3,c0,一,一,Bronze,B00004,pad,lee,hanziyuan,72.810930,288.0,Oracle
4,c0,一,一,Bronze,B00005,pad,lee,hanziyuan,70.373133,288.0,Oracle

In [138]:
new = new.rename({"perimetric_complexity": "new_perimetric_complexity", "pixel_complexity": "new_pixel_complexity"}, axis=1)
print(new.shape)
new.head()

(2979388, 9)

,original_character,simplified_character,period,image_ID,dataset,scale_method,skeletonise_method,new_perimetric_complexity,new_pixel_complexity
0,一,一,Bronze,B00001,hzy,stretch,lee,127.581136,416.0
1,一,一,Bronze,B00002,hzy,stretch,lee,124.451226,431.0
2,一,一,Bronze,B00003,hzy,stretch,lee,123.139566,370.0
3,一,一,Bronze,B00004,hzy,stretch,lee,122.670068,377.0
4,一,一,Bronze,B00005,hzy,stretch,lee,132.562733,431.0

In [139]:
df = old.merge(new, on=["original_character", "scale_method", "image_ID", "period"])
print(df.shape)
different = df[df["old_pixel_complexity"] != df["new_pixel_complexity"]][["original_character", "dataset_x", "period", "image_ID", "scale_method", "skeletonise method", "old_perimetric_complexity", "new_perimetric_complexity", "old_pixel_complexity", "new_pixel_complexity"]]
print(different.shape)
different.head()

(1413309, 16)
(62878, 10)

,original_character,dataset_x,period,image_ID,scale_method,skeletonise method,old_perimetric_complexity,new_perimetric_complexity,old_pixel_complexity,new_pixel_complexity
1006,拜,hanziyuan,Bronze,B16335,pad,lee,360.043913,363.393276,1246.0,1261.0
2294,方,hanziyuan,Oracle,J20392,pad,lee,167.437141,162.694109,622.0,607.0
5505,梦,hanziyuan,Oracle,J18010,pad,lee,287.118170,286.899189,1080.0,1079.0
5828,正,hanziyuan,Oracle,J03367,pad,lee,207.481076,207.919708,792.0,794.0
9861,田,hanziyuan,Oracle,J28588,pad,lee,309.381722,319.224546,1228.0,1277.0

In [146]:
different.to_csv("unexplained_complexity_differences.csv")

In [142]:
different[different["scale_method"]=="stretch"]

,original_character,dataset_x,period,image_ID,scale_method,skeletonise method,old_perimetric_complexity,new_perimetric_complexity,old_pixel_complexity,new_pixel_complexity
703207,一,hanziyuan,Bronze,B00005,stretch,lee,132.557582,132.562733,430.0,431.0
703213,一,hanziyuan,Bronze,B00011,stretch,lee,123.416267,123.459753,451.0,453.0
703220,一,hanziyuan,Seal,S00001,stretch,lee,142.048507,142.055967,468.0,469.0
703230,愧,hanziyuan,Bronze,B17078,stretch,lee,331.649302,331.431014,1214.0,1213.0
703236,愧,hanziyuan,Seal,S09357,stretch,lee,503.984862,504.499295,1826.0,1827.0
...,...,...,...,...,...,...,...,...,...,...
1413241,愉,traditional_handwritten,Traditional,4,stretch,lee,373.459362,373.240548,1395.0,1394.0
1413255,愉,traditional_handwritten,Traditional,7,stretch,lee,356.658579,356.636401,1311.0,1310.0
1413288,意,traditional_handwritten,Traditional,36,stretch,lee,371.235949,371.453453,1323.0,1324.0
1413304,意,traditional_handwritten,Traditional,50,stretch,lee,334.139227,334.116973,1229.0,1228.0
1413307,意,traditional_handwritten,Traditional,8,stretch,lee,314.024576,314.010920,1082.0,1081.0

In [143]:
different["perimetric_difference"] = [abs(row["old_perimetric_complexity"] - row["new_perimetric_complexity"]) for _, row in different.iterrows()]
different["pixel_difference"] = [abs(row["old_pixel_complexity"] - row["new_pixel_complexity"]) for _, row in different.iterrows()]

In [145]:
df = different[(different["scale_method"] == "stretch")]
df.iloc[df["perimetric_difference"].argmax()]

original_character                                降
dataset_x                    simplified_handwritten
period                                   Simplified
image_ID                                         80
scale_method                                stretch
skeletonise method                              lee
old_perimetric_complexity                256.566381
new_perimetric_complexity                269.004638
old_pixel_complexity                          924.0
new_pixel_complexity                          972.0
perimetric_difference                     12.438258
pixel_difference                               48.0
Name: 977313, dtype: object

In [123]:
different[(different["image_ID"]) == "J28588"]

,original_character,dataset_x,period,image_ID,scale_method,skeletonise method,old_perimetric_complexity,new_perimetric_complexity,old_pixel_complexity,new_pixel_complexity,perimetric_difference,pixel_difference
9861,田,hanziyuan,Oracle,J28588,pad,lee,309.381722,319.224546,1228.0,1277.0,9.842824,49.0

In [124]:
df = different[(different["scale_method"] == "pad")]
df.iloc[df["pixel_difference"].argmax()]

original_character                    田
dataset_x                     hanziyuan
period                           Oracle
image_ID                         J28588
scale_method                        pad
skeletonise method                  lee
old_perimetric_complexity    309.381722
new_perimetric_complexity    319.224546
old_pixel_complexity             1228.0
new_pixel_complexity             1277.0
perimetric_difference          9.842824
pixel_difference                   49.0
Name: 9861, dtype: object

In [108]:
not_trad

,original_character,dataset_x,period,image_ID,scale_method,skeletonise method,old_perimetric_complexity,new_perimetric_complexity,old_pixel_complexity,new_pixel_complexity,perimetric_difference,pixel_difference
1006,拜,hanziyuan,Bronze,B16335,pad,lee,360.043913,363.393276,1246.0,1261.0,3.349363,15.0
2294,方,hanziyuan,Oracle,J20392,pad,lee,167.437141,162.694109,622.0,607.0,4.743033,15.0
5505,梦,hanziyuan,Oracle,J18010,pad,lee,287.118170,286.899189,1080.0,1079.0,0.218981,1.0
5828,正,hanziyuan,Oracle,J03367,pad,lee,207.481076,207.919708,792.0,794.0,0.438633,2.0
9861,田,hanziyuan,Oracle,J28588,pad,lee,309.381722,319.224546,1228.0,1277.0,9.842824,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...
480963,思,simplified_handwritten,Simplified,105,pad,lee,260.444936,261.073446,861.0,862.0,0.628510,1.0
481266,怡,simplified_handwritten,Simplified,33,pad,lee,265.718454,265.646051,996.0,997.0,0.072403,1.0
484712,悍,simplified_handwritten,Simplified,92,pad,lee,293.221797,292.702652,1020.0,1019.0,0.519144,1.0
484814,悔,simplified_handwritten,Simplified,55,pad,lee,332.348083,332.980695,1232.0,1234.0,0.632612,2.0
485710,情,simplified_handwritten,Simplified,18,pad,lee,260.501205,260.531640,1026.0,1027.0,0.030435,1.0

In [107]:
not_trad = different[different["period"] != "Traditional"]
not_trad[not_trad["pixel_difference"] > 0][not_trad["dataset_x"]!="hanziyuan"].shape

(205, 12)

In [88]:
dfa.sort_values(by="pixel_difference", ascending=False)

,original_character,dataset_x,period,image_ID,scale_method,skeletonise method,old_perimetric_complexity,new_perimetric_complexity,old_pixel_complexity,new_pixel_complexity,perimetric_difference,pixel_difference
9861,田,hanziyuan,Oracle,J28588,pad,lee,309.381722,319.224546,1228.0,1277.0,9.842824e+00,49.0
427060,圆,simplified_handwritten,Simplified,143,pad,lee,437.610337,450.387986,1664.0,1706.0,1.277765e+01,42.0
260783,降,simplified_handwritten,Simplified,80,pad,lee,220.698057,229.571536,798.0,831.0,8.873479e+00,33.0
401545,陀,simplified_handwritten,Simplified,74,pad,lee,286.500111,276.945498,1002.0,970.0,9.554613e+00,32.0
206333,讽,simplified_handwritten,Simplified,79,pad,lee,297.731975,308.492782,1062.0,1089.0,1.076081e+01,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...
149205,紧,simplified_handwritten,Simplified,29,pad,lee,255.148541,255.148541,845.0,845.0,2.842171e-14,0.0
149678,纠,simplified_handwritten,Simplified,71,pad,lee,214.656987,214.656987,773.0,773.0,5.684342e-14,0.0
149725,红,simplified_handwritten,Simplified,113,pad,lee,218.261958,218.261958,785.0,785.0,2.842171e-14,0.0
149870,纤,simplified_handwritten,Simplified,115,pad,lee,224.817834,224.817834,735.0,735.0,2.842171e-14,0.0
487771,意,simplified_handwritten,Simplified,75,pad,lee,234.856414,234.856414,813.0,813.0,5.684342e-14,0.0